# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-19 12:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2019, 11, 19), null=True, verbose_name='Date de la demande')),
                ('status', models.IntegerField(choices=[(0, 'En cours'), (1, 'Validée'), (2, 'Refusée')], default=0, verbose_name='Staut de la demande')),
                ('dpo_cnil', models.FileField(upload_to='commandes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'doc', 'docx', 'odt'])], verbose_name='DPO CNIL*')),
                ('acte_engagement', models.FileField(upload_to='commandes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'doc', 'docx', 'odt'])], verbose_name="Acte d'engagement*")),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
            ],
            options={
                'verbose_name': 'Commande de fichiers fonciers',
                'verbose_name_plural': 'Commandes de fichiers fonciers',
            },
        ),
    ]
