# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-14 10:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idgo_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteDcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('sync_frequency', models.CharField(blank=True, choices=[('never', 'Jamais'), ('daily', 'Quotidienne (tous les jours à minuit)'), ('weekly', 'Hebdomadaire (tous les lundi)'), ('bimonthly', 'Bimensuelle (1er et 15 de chaque mois)'), ('monthly', 'Mensuelle (1er de chaque mois)'), ('quarterly', 'Trimestrielle (1er des mois de janvier, avril, juillet, octobre)'), ('biannual', 'Semestrielle (1er janvier et 1er juillet)'), ('annual', 'Annuelle (1er janvier)')], default='never', max_length=20, null=True, verbose_name='Fréquence de synchronisation')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Organisation')),
            ],
            options={
                'verbose_name': 'Catalogue DCAT distant',
                'verbose_name_plural': 'Catalogues DCAT distants',
            },
        ),
        migrations.CreateModel(
            name='RemoteDcatDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_dataset', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True, verbose_name='Jeu de données distant')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_on', models.DateTimeField(auto_now_add=True, verbose_name='Mis-à-jour le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creates_dataset_from_remote_dcat', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.Dataset')),
                ('remote_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idgo_admin.RemoteDcat')),
            ],
            options={
                'verbose_name': 'Jeu de données moissonné',
                'verbose_name_plural': 'Jeux de données moissonnés',
            },
        ),
        migrations.AlterUniqueTogether(
            name='remotedcatdataset',
            unique_together=set([('remote_instance', 'dataset')]),
        ),
    ]
