# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-19 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IHMSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100, unique=True, verbose_name="Identifiant de l'objet")),
                ('contents', models.TextField(verbose_name='Contenu')),
                ('target', models.CharField(blank=True, choices=[('ckan', 'Ckan'), ('admin', 'Admin')], default='ckan', max_length=100, null=True, verbose_name='Cible')),
                ('activate', models.BooleanField(default=False, verbose_name='Activer')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Configuration particulière des IHM',
                'verbose_name_plural': 'Configurations particulières des IHM',
            },
        ),
    ]
